import { X, Download, Copy } from 'lucide-react';

const TranscriptModal = ({ resource, onClose }) => {
  // Simulated transcript data
  const transcript = `
[00:00:00] Welcome to this comprehensive course on ${resource.title.split(' - ')[0]}.

[00:02:15] In this first section, we'll cover the fundamental concepts and principles that form the foundation of this topic.

[00:05:30] Let's start by understanding the core terminology and key definitions that you'll encounter throughout this course.

[00:10:45] Now that we have the basics covered, let's dive deeper into the practical applications.

[00:15:20] Here's an example that demonstrates how these concepts work in real-world scenarios.

[00:20:10] As you can see from this demonstration, the principles we've discussed are highly applicable.

[00:25:35] Let's now explore some advanced techniques and optimization strategies.

[00:30:00] This concludes our introduction. In the next section, we'll build upon these foundations.
  `.trim();

  const handleCopy = () => {
    navigator.clipboard.writeText(transcript);
    alert('Transcript copied to clipboard!');
  };

  const handleDownload = () => {
    const blob = new Blob([transcript], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${resource.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_transcript.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-fade-in">
      <div className="bg-white rounded-2xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-hidden animate-scale-in">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200">
          <div>
            <h2 className="text-2xl font-bold text-gray-900">Video Transcript</h2>
            <p className="text-sm text-gray-500 mt-1">{resource.title}</p>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 rounded-lg transition-colors duration-200"
          >
            <X size={24} className="text-gray-500" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto max-h-[calc(90vh-180px)]">
          <div className="prose max-w-none">
            <pre className="whitespace-pre-wrap font-sans text-sm text-gray-700 leading-relaxed">
              {transcript}
            </pre>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between p-6 border-t border-gray-200 bg-gray-50">
          <div className="text-sm text-gray-500">
            Generated by AI • {transcript.split('\n').length} lines
          </div>
          <div className="flex space-x-3">
            <button
              onClick={handleCopy}
              className="flex items-center space-x-2 px-4 py-2 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors duration-200"
            >
              <Copy size={18} />
              <span>Copy</span>
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center space-x-2 px-4 py-2 bg-darkBlue-600 text-white rounded-lg hover:bg-darkBlue-700 transition-colors duration-200"
            >
              <Download size={18} />
              <span>Download</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TranscriptModal;

